[package]
name = "ccttrs"
version = "0.1.1"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "ccttrs_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
indexmap = { version = "1.9.3", features = ["std"] }


[dependencies]
tauri = { version = "=2.10.1", features = [] }
tauri-runtime = "=2.10.1"
tauri-runtime-wry = "=2.10.1"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
rayon = "1"
sysinfo = "0.30"
tauri-plugin-store = "=2.4.2"
tauri-plugin-dialog = "=2.6.0"
md5 = "0.8.0"
indexmap = { version = "1.9.3", features = ["std"] }

[profile.dev]
debug = 0
strip = true

[profile.release]
strip = true
lto = true
codegen-units = 1


